general.import = ["~/.cache/wal/alacritty.toml"]

[env]
TERM = "xterm-256color"

[window]
padding = { x = 8, y = 8 }
decorations = "None"

# NOTE: alacritty doesn't support ligatures, so all your btop braille symbols
# will be fuced anyway. https://github.com/alacritty/alacritty/issues/5485
[font]
normal = { family =  "kode mono", style = "Regular" }
size = 12.0
# normal = { family =  "daddytimemono nerd font", style = "Regular" }
# normal = { family =  "nova mono", style = "Regular" } # size 12
# normal = { family =  "monofur", style = "Regular" } # size 14

[keyboard]
bindings = [
         { key = "Space", mods = "Control", action = "ToggleViMode" },
]
